# Generated by Django 4.0 on 2022-06-27 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('socialapp', '0005_instantmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instantmessage',
            name='sender',
        ),
        migrations.AddField(
            model_name='instantmessage',
            name='sender',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.user'),
        ),
    ]
