# Generated by Django 4.0 on 2022-06-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('socialapp', '0007_alter_instantmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessage',
            name='sender',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='auth.user'),
        ),
    ]
