# Generated by Django 4.0 on 2022-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0012_remove_instantmessage_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instantmessage',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='instantmessage',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
