# Generated by Django 4.0 on 2022-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0013_instantmessage_created_instantmessage_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instantmessage',
            name='message',
            field=models.TextField(),
        ),
    ]
